##############################################################################
# Plots of grams of alcohol per day - DRINKERS
# This script generates takes the data generated by MAIHDA and generates descriptive plots of the results
##############################################################################

######################################################################## Set-up
setwd("C:/Users/cmp21seb/Documents/SIMAH/")
code <- "SIMAH_code/nhis/intersectionality/MAIHDA alcohol/"
inputs <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/inputs/"
models <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/models/"
outputs <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/outputs/"

library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(labelled)
library(haven)
library(ggplot2)
library(forcats)

## Bias toward non-scientific notation
options(scipen=10)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))

##### Plots

# Read in data
plot_data <- readRDS(paste0(outputs,"grams drinkers/results_grams_drinkers_corrected_cis.rds"))

# Prep data for plotting
plot_data <- plot_data %>%
  mutate(sex=ifelse(grepl("Female",intersectional_names),"Women","Men"),
         race=ifelse(grepl("Asian",intersectional_names),"Asian",
                     ifelse(grepl("Black", intersectional_names),"Black",
                            ifelse(grepl("AI/AN", intersectional_names), "AI/AN",
                                ifelse(grepl("Multiple race", intersectional_names), "Multiple race",
                                   ifelse(grepl("Hispanic", intersectional_names), "Hispanic","White"))))),
         race=factor(race, levels=c("Hispanic", "AI/AN", "Asian","Black", "Multiple race", "White")),
         education=ifelse(grepl("high school", intersectional_names), "high school or less",
                          ifelse(grepl("some college", intersectional_names), "some college", "college+")),
         education=factor(education,levels=c("high school or less", "some college", "college+")),
         age=ifelse(grepl("21-24", intersectional_names), "21-24",
                    ifelse(grepl("25-59", intersectional_names), "25-59", "60+")))


# Plots of additive only - men
male_grams_add <- plot_data %>%
  filter(sex=="Men") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estmn), colour = "darkblue") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour="darkblue") +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  theme(strip.background = element_rect(fill = "lightblue")) +
  ggtitle("The influence of interaction effects on estimated alcohol consumption: Men")+
  labs(y= "Estimated grams per day") 
male_grams_add
ggsave(paste0(outputs,"grams drinkers/plot grams males, additive_updated CIs.png"), dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates - men
male_grams_add_vs_mul <- plot_data %>%
  filter(sex=="Men") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estAmn), colour = "lightblue", alpha = 0.5) +
  geom_errorbar(aes(ymin = estAlo,
                    ymax = estAhi),
                colour="lightblue") +
  geom_point(aes(y=estmn), colour = "darkblue") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour="darkblue") +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  theme(strip.background = element_rect(fill = "lightblue")) +
  ggtitle("The influence of interaction effects on estimated alcohol consumption: Men")+
  labs(y= "Estimated grams per day") 
  male_grams_add_vs_mul
ggsave(paste0(outputs,"grams drinkers/plot grams males, additive versus total estimates updated cis.png"), dpi=300, width=33, height=19, units="cm")

# Plots of additive only  - women
female_grams_add <- plot_data %>%
  filter(sex=="Women") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estmn), colour = "darkblue") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour = "darkblue") +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  ggtitle("The influence of interaction effects on estimated alcohol consumption: Women")
female_grams_add
ggsave(paste0(outputs,"grams drinkers/plot grams females, additive only updated CIs.png"), dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates - women
female_grams_add_vs_mul <- plot_data %>%
  filter(sex=="Women") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estAmn), colour = "lightblue") +
  geom_errorbar(aes(ymin = estAlo,
                    ymax = estAhi),
                colour="lightblue") +
  geom_point(aes(y=estmn), colour = "darkblue") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour = "darkblue") +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  theme(strip.background = element_rect(fill = "lightblue")) +
  ggtitle("The influence of interaction effects on estimated alcohol consumption: Women")
female_grams_add_vs_mul
ggsave(paste0(outputs,"grams drinkers/plot grams females, additive versus total estimates updated CIs.png"), dpi=300, width=33, height=19, units="cm")

# Plot of additive versus total estimates, both genders together

# Create offsets for the x-axis positions
plot_data <- plot_data %>%
  mutate(education_men_add = ifelse(sex == "Men", as.numeric(education) - 0.15, as.numeric(education)),
         education_men_total = ifelse(sex == "Men", as.numeric(education) + 0.15, as.numeric(education)),
         education_women_add = ifelse(sex == "Women", as.numeric(education) - 0.15, as.numeric(education)),
         education_women_total = ifelse(sex == "Women", as.numeric(education) + 0.15, as.numeric(education)))

combined_plot <- plot_data %>%
  ggplot() +
  geom_point(data = filter(plot_data, sex == "Men"), aes(x = education_men_add, y = estAmn, color = "Men, additive effects only"), alpha = 0.5) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(x = education_men_add, ymin = estAlo, ymax = estAhi, color = "Men, additive effects only"), width = 0.3) +
  geom_point(data = filter(plot_data, sex == "Men"), aes(x = education_men_total, y = estmn, color = "Men, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(x = education_men_total, ymin = estlo, ymax = esthi, color = "Men, total effects"), width = 0.3) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(x = education_women_add, y = estAmn, color = "Women, additive effects only"), alpha = 0.5) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(x = education_women_add, ymin = estAlo, ymax = estAhi, color = "Women, additive effects only"), width = 0.3) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(x = education_women_total, y = estmn, color = "Women, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(x = education_women_total, ymin = estlo, ymax = esthi, color = "Women, total effects"), width = 0.3) +
  facet_grid(cols = vars(race), rows = vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, size = 12, hjust = 0.5, vjust = 0.5),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 12),
        plot.title = element_text(size = 16)) +
  theme(strip.background = element_rect(fill = "lightblue")) +
  # ggtitle("The influence of interaction effects on estimated alcohol consumption") +
  labs(y = "Estimated grams per day", color = "Sex") +
  scale_color_manual(values = c("Men, additive effects only" = "lightblue", "Men, total effects" = "darkblue", "Women, additive effects only" = "orange", "Women, total effects" = "darkred")) +
  guides(color = guide_legend(title = NULL, ncol = 4)) +
  scale_x_continuous(breaks = c(1, 2, 3), labels = c("low", "med.", "high")) +
  scale_y_continuous(breaks = seq(0, max(plot_data$esthi), by = 5))

combined_plot
ggsave(paste0(outputs,"grams drinkers/plot grams both sexes, additive versus total estimates updated CIs.png"), dpi=300, width=33, height=19, units="cm")

# Plot of total estimates only, both genders together
combined_plot_total <- plot_data %>%
  ggplot(aes(x = education)) +
  geom_point(data = filter(plot_data, sex == "Men"), aes(y = estmn, color = "Men, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(ymin = estlo, ymax = esthi, color = "Men, total effects")) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(y = estmn, color = "Women, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(ymin = estlo, ymax = esthi, color = "Women, total effects")) +
  facet_grid(cols = vars(race), rows = vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, size=12),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 12),
        plot.title = element_text(size = 16)) +
  theme(strip.background = element_rect(fill = "lightblue")) +
  labs(y = "Estimated grams per day", color = "Sex") +
  scale_color_manual(values = c("Men, total effects" = "darkblue", "Women, total effects" = "darkred")) +
  guides(color = guide_legend(title = NULL, ncol = 4)) +
  scale_x_discrete(labels = c("high school or less" = "low", "some college" = "med.", "college+" = "high"))+
  scale_y_continuous(breaks = seq(0, max(plot_data$esthi), by = 5))
combined_plot_total
ggsave(paste0(outputs,"grams drinkers/plot grams both sexes, total estimates only updated CIs.png"), dpi=300, width=33, height=19, units="cm")

# Calculate the number of strat for whom there are significant interaction effects (i.e. CIs don't cross zero)
significant_interactions <- plot_data %>% filter(estIlo<0 & estIhi <0 | estIlo >0 & estIhi>0)




