##############################################################################
# Plots of grams of alcohol per day - DRINKERS
# This script generates takes the data generated by MAIHDA and generates descriptive plots of the results
##############################################################################

######################################################################## Set-up
setwd("C:/Users/cmp21seb/Documents/SIMAH/")
code <- "SIMAH_code/nhis/intersectionality/MAIHDA alcohol/"
inputs <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/inputs/"
models <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/models/"
outputs <- "SIMAH_workplace/nhis/intersectionality/MAIHDA alcohol/outputs/"

library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(labelled)
library(haven)
library(ggplot2)
library(forcats)

## Bias toward non-scientific notation
options(scipen=10)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))

##### Plots

# Read in data
plot_data <- readRDS(paste0(outputs,"binary drinking status/results binary drinking status.rds"))

# Prep data for plotting
plot_data <- plot_data %>%
  mutate(sex=ifelse(grepl("Female",intersectional_names),"Women","Men"),
         race=ifelse(grepl("Asian",intersectional_names),"Asian",
                     ifelse(grepl("Black", intersectional_names),"Black",
                            ifelse(grepl("AI/AN", intersectional_names), "AI/AN",
                                ifelse(grepl("Multiple race", intersectional_names), "Multiple race",
                                   ifelse(grepl("Hispanic", intersectional_names), "Hispanic","White"))))),
         race=factor(race, levels=c("Hispanic", "AI/AN", "Asian","Black", "Multiple race", "White")),
         education=ifelse(grepl("high school", intersectional_names), "high school or less",
                          ifelse(grepl("some college", intersectional_names), "some college", "college+")),
         education=factor(education,levels=c("high school or less", "some college", "college+")),
         age=ifelse(grepl("21-24", intersectional_names), "21-24",
                    ifelse(grepl("25-59", intersectional_names), "25-59", "60+")))

# Plot of additive versus total estimates, both genders together
combined_plot <- plot_data %>%
  ggplot(aes(x = education)) +
  geom_point(data = filter(plot_data, sex == "Men"), aes(y = pAmn, color = "Men, additive effects only"), alpha = 0.5) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(ymin = pAlo, ymax = pAhi, color = "Men, additive effects only")) +
  geom_point(data = filter(plot_data, sex == "Men"), aes(y = pmn, color = "Men, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(ymin = plo, ymax = phi, color = "Men, total effects")) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(y = pAmn, color = "Women, additive effects only"), alpha = 0.5) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(ymin = pAlo, ymax = pAhi, color = "Women, additive effects only")) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(y = pmn, color = "Women, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(ymin = plo, ymax = phi, color = "Women, total effects")) +
  facet_grid(cols = vars(race), rows = vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, size=12),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 12),
        plot.title = element_text(size = 16)) +
  theme(strip.background = element_rect(fill = "lightblue")) +
  labs(y = "% current drinkers", color = "Sex") +
  scale_color_manual(values = c("Men, additive effects only" = "lightblue", "Men, total effects" = "darkblue", "Women, additive effects only" = "orange", "Women, total effects" = "darkred")) +
  guides(color = guide_legend(title = NULL, ncol = 4)) +
  scale_x_discrete(labels = c("high school or less" = "low", "some college" = "med.", "college+" = "high")) + 
  scale_y_continuous(limits = c(0, 100))

combined_plot
ggsave(paste0(outputs,"binary drinking status/plot binary drinking status both sexes, additive versus total estimates.png"), dpi=300, width=33, height=19, units="cm")


# Plot of total estimates only, both genders together
combined_plot_total <- plot_data %>%
  ggplot(aes(x = education)) +
  # geom_point(data = filter(plot_data, sex == "Men"), aes(y = pmn, color = "Men, additive effects only"), alpha = 0.5) +
  # geom_errorbar(data = filter(plot_data, sex == "Men"), aes(ymin = pAlo, ymax = pAhi, color = "Men, additive effects only")) +
  geom_point(data = filter(plot_data, sex == "Men"), aes(y = pmn, color = "Men, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Men"), aes(ymin = plo, ymax = phi, color = "Men, total effects")) +
  # geom_point(data = filter(plot_data, sex == "Women"), aes(y = pAmn, color = "Women, additive effects only"), alpha = 0.5) +
  # geom_errorbar(data = filter(plot_data, sex == "Women"), aes(ymin = pAlo, ymax = pAhi, color = "Women, additive effects only")) +
  geom_point(data = filter(plot_data, sex == "Women"), aes(y = pmn, color = "Women, total effects")) +
  geom_errorbar(data = filter(plot_data, sex == "Women"), aes(ymin = plo, ymax = phi, color = "Women, total effects")) +
  facet_grid(cols = vars(race), rows = vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 90, size=12),
        legend.position = "bottom",
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 12),
        plot.title = element_text(size = 16)) +
  theme(strip.background = element_rect(fill = "lightblue")) +
#  ggtitle("The influence of interaction effects on estimated proportion of current drinkers") +
  labs(y = "% current drinkers", color = "Sex") +
  scale_color_manual(values = c("Men, total effects" = "darkblue", "Women, total effects" = "darkred")) +
  guides(color = guide_legend(title = NULL, ncol = 4)) +
  scale_x_discrete(labels = c("high school or less" = "low", "some college" = "med.", "college+" = "high")) + 
  scale_y_continuous(limits = c(0, 100))

combined_plot_total
ggsave(paste0(outputs,"binary drinking status/plot binary drinking status both sexes, total estimates only.png"), dpi=300, width=33, height=19, units="cm")











