# This script takes the data generated by MAIHDA and generates descriptive plots of the results

library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(labelled)
library(haven)
library(ggplot2)
library(forcats)
library(patchwork)

## Bias toward non-scientific notation
options(scipen=10)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))

# Read in data
data <- read_rds("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/results tables/MAIHDA_transformed_estimates_grams_MCMC.rds")

# Generate columns for race, sex, education and generation (as want them named in the graph) from column 'intersectional names'
data <- data %>%
  mutate(sex=ifelse(grepl("F",intersectional_names),"Female","Male"),
         race=ifelse(grepl("Non-Hispanic Asian",intersectional_names),"Asian",
              ifelse(grepl("Non-Hispanic Black", intersectional_names),"Black",
              ifelse(grepl("Non-Hispanic Other", intersectional_names), "Other",
              ifelse(grepl("White", intersectional_names), "White","Hispanic")))),
         education=ifelse(grepl("low edu.", intersectional_names), "low edu.",
              ifelse(grepl("med. edu.", intersectional_names), "medium edu.", "high edu.")),
         education=factor(education,levels=c("low edu.", "medium edu.", "high edu.")))

## 1. Residuals

# Plots of residuals (log transformed)
male_residuals_log <- data %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=age_3_cats, y=residuals, colour=decade)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = residuals - (1.96*residualsSE),
                    ymax = residuals + (1.96*residualsSE)),
                position=position_dodge(width=0.8)) +
  facet_grid(cols=vars(education),rows=vars(race)) +
  theme(axis.title.x = element_blank(), legend.position = "bottom") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  ggtitle("Males: Residuals (log)")
male_residuals_log

female_residuals_log <- data %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=age_3_cats, y=residuals, colour=decade)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = residuals - (1.96*residualsSE),
                    ymax = residuals + (1.96*residualsSE)),
                position=position_dodge(width=0.8)) +
  facet_grid(cols=vars(education),rows=vars(race)) +
  theme(axis.title.x = element_blank(), legend.position = "bottom") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  ggtitle("Females: Residuals (log)")
female_residuals_log

# Count number of intersections with residual CIs that don't include 0
interactions <- data %>% 
  mutate(
    residual_lower_CI = residuals - (1.96*residualsSE),
    residual_upper_CI = residuals + (1.96*residualsSE),
    significance_and_direction = case_when(residual_lower_CI > 0 & residual_upper_CI > 0 ~ "yes_drinks_more",
                          residual_lower_CI < 0 & residual_upper_CI < 0 ~ "yes_drinks_less", 
                          residual_lower_CI < 0 & residual_upper_CI > 0 ~ "no")) 

interactions <- interactions %>%
  filter(significance_and_direction!="no") %>%
  select(intersections, sex, decade, race, age_3_cats, education, residual_lower_CI, residual_upper_CI, significance_and_direction)

saveRDS(interactions, "C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/results tables/intersections_with_sig_interactions.RDS")
# 49 intersections with significant interactions


## 2. Plots of estimated means and standard errors (post back-transformation)

# Plot males
male_plot <- data %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=decade, y=back_transformed_estimate, colour=education)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = back_transformed_CI_lower,
                    ymax = back_transformed_CI_upper),
                    position=position_dodge(width=0.8)) +
                facet_grid(cols=vars(race),rows=vars(age_3_cats)) +
  theme(axis.title.x = element_blank(), legend.position = "bottom", axis.text=element_text(size=6))+
  ggtitle("Men")+
  labs(y= "Estimated grams per day", colour = "Educational attainment") 
male_plot
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/MAIHDA_male_estimated_grams.png", dpi=300, width=33, height=19, units="cm")

female_plot <- data %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=decade, y=back_transformed_estimate, colour=education)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = back_transformed_CI_lower,
                    ymax = back_transformed_CI_upper),
                    position=position_dodge(width=0.8)) +
                facet_grid(cols=vars(race),rows=vars(age_3_cats)) +
  theme(axis.title.x = element_blank(), legend.position = "bottom", axis.text=element_text(size=6))+
  ggtitle("Women") +
  labs(y= "Estimated grams per day", colour = "Educational attainment")
female_plot
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/MAIHDA_female_estimated_grams.png", dpi=300, width=33, height=19, units="cm")
