# This script generates takes the data generated by MAIHDA and generates descriptive plots of the results

# MAIN

library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(labelled)
library(haven)
library(ggplot2)
library(forcats)

## Bias toward non-scientific notation
options(scipen=10)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))

##### Plots for full sample

# Read in data
plot_data_MAIN <- readRDS("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/results tables/new spec August 2023/HED/mdata_results_MAIN.rds")

# Prep data for plotting
plot_data_MAIN <- plot_data_MAIN %>%
  mutate(sex=ifelse(grepl("Female",intersectional_names),"Female","Male"),
         race=ifelse(grepl("Asian",intersectional_names),"NH Asian",
                     ifelse(grepl("Black", intersectional_names),"NH Black",
                            ifelse(grepl("AI/AN", intersectional_names), "NH AI/AN",
                                ifelse(grepl("Multiple race", intersectional_names), "NH Multiple race",
                                   ifelse(grepl("Hispanic White", intersectional_names), "Hispanic White","NH White"))))),
         race=factor(race, levels=c("Hispanic White", "NH AI/AN", "NH Asian","NH Black", "NH Multiple race", "NH White")),
         education=ifelse(grepl("high school", intersectional_names), "high school or less",
                          ifelse(grepl("some college", intersectional_names), "some college", "college+")),
         education=factor(education,levels=c("high school or less", "some college", "college+")),
         age=ifelse(grepl("21-24", intersectional_names), "21-24",
                    ifelse(grepl("25-59", intersectional_names), "25-59", "60+")))

# Plots of predicted % of HEDs - separate for males and females
male_HED_probability <- plot_data_MAIN %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=education, y=pmn)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = plo,
                    ymax = phi),
                    position=position_dodge(width=0.8)) +
  ylim(0, 100) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90),
        legend.position = "bottom") +
  ggtitle("Percentage of men estimated to be HEDs by intersectional category")+
  labs(y= "Percentage estimated to be HEDs")
male_HED_probability
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/HED/estimated_HEDs_males_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plot females
female_HED_probability <- plot_data_MAIN %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=education, y=pmn)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = plo,
                    ymax = phi),
                position=position_dodge(width=0.8)) +
  ylim(0, 100) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90),
        legend.position = "bottom") +
  ggtitle("Percentage of women estimated to be HEDs by intersectional category")+
  labs(y= "Percentage estimated to be HEDs")
female_HED_probability
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/HED/estimated_HEDs_females_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates
male_HED_add_vs_mul <- plot_data_MAIN %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=race)) +
  geom_point(aes(y=pAmn), colour = "grey") +
  geom_errorbar(aes(ymin = pAlo,
                    ymax = pAhi),
                colour="grey") +
  geom_point(aes(y=pmn), colour = "black") +
  geom_errorbar(aes(ymin = plo,
                    ymax = phi),
                colour = "black") +
  ylim(0, 75) +
  facet_grid(cols=vars(education),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  ggtitle("Percentage of men estimated to be HEDs by intersectional category")+
  labs(y= "Percentage estimated to be HEDs") +
  labs(caption = "Grey: estimate based on additive effects only  
Black: Estimate based on additive & interaction effects")
  male_HED_add_vs_mul
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/HED/estimated_HEDs_males_add_vs_mult_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates
female_HED_add_vs_mul <- plot_data_MAIN %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=race)) +
  geom_point(aes(y=pAmn), colour = "grey") +
  geom_errorbar(aes(ymin = pAlo,
                    ymax = pAhi),
                colour="grey") +
  geom_point(aes(y=pmn), colour = "black") +
  geom_errorbar(aes(ymin = plo,
                    ymax = phi),
                colour = "black") +
  ylim(0, 100) +
  facet_grid(cols=vars(education),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  ggtitle("Percentage of women estimated to be HEDs by intersectional category")+
  labs(y= "Percentage estimated to be HEDs") +
  labs(caption = "Grey: estimate based on additive effects only  
Black: Estimate based on additive & interaction effects")
female_HED_add_vs_mul
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/HED/estimated_HEDs_females_add_vs_mult_MAIN.png", dpi=300, width=33, height=19, units="cm")

