# This script generates takes the data generated by MAIHDA and generates descriptive plots of the results

# MAIN

library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(labelled)
library(haven)
library(ggplot2)
library(forcats)

## Bias toward non-scientific notation
options(scipen=10)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))

##### Plots for full sample

# Read in data
plot_data_MAIN <- readRDS("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/results tables/new spec August 2023/grams/mdata_results_grams_MAIN.rds")

# Prep data for plotting
plot_data_MAIN <- plot_data_MAIN %>%
  mutate(sex=ifelse(grepl("Female",intersectional_names),"Female","Male"),
         race=ifelse(grepl("Asian",intersectional_names),"NH Asian",
                     ifelse(grepl("Black", intersectional_names),"NH Black",
                            ifelse(grepl("AI/AN", intersectional_names), "NH AI/AN",
                                ifelse(grepl("Multiple race", intersectional_names), "NH Multiple race",
                                   ifelse(grepl("Hispanic White", intersectional_names), "Hispanic White","NH White"))))),
         race=factor(race, levels=c("Hispanic White", "NH AI/AN", "NH Asian","NH Black", "NH Multiple race", "NH White")),
         education=ifelse(grepl("high school", intersectional_names), "high school or less",
                          ifelse(grepl("some college", intersectional_names), "some college", "college+")),
         education=factor(education,levels=c("high school or less", "some college", "college+")),
         age=ifelse(grepl("21-24", intersectional_names), "21-24",
                    ifelse(grepl("25-59", intersectional_names), "25-59", "60+")))

# Plots of predicted grams - separate for males and females
male_grams <- plot_data_MAIN %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=education, y=estmn)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                    position=position_dodge(width=0.8)) +
  ylim(0, 5) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90),
        legend.position = "bottom") +
  ggtitle("Average daily alcohol consumption by intersectional category, Men")+
  labs(y= "Estimated grams per day")
male_grams
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/grams/estimated_grams_males_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plot females
female_grams <- plot_data_MAIN %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=education, y=estmn)) +
  geom_point(position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                position=position_dodge(width=0.8)) +
  ylim(0, 5) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90),
        legend.position = "bottom") +
  ggtitle("Average daily alcohol consumption by intersectional category, Women")+
  labs(y= "Estimated grams per day")
female_grams
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/grams/estimated_grams_females_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates
male_grams_add_vs_mul <- plot_data_MAIN %>%
  filter(sex=="Male") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estAmn), colour = "grey", alpha = 0.5) +
  geom_errorbar(aes(ymin = estAlo,
                    ymax = estAhi),
                colour="grey") +
  geom_point(aes(y=estmn), colour = "black") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour="black") +
  ylim(0, 4) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  ggtitle("Average daily alcohol consumption by intersectional category, for Men")+
  labs(y= "Estimated grams per day") +
  labs(caption = "Grey: estimate based on additive effects only  
Black: Estimate based on additive & interaction effects")
  male_grams_add_vs_mul
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/grams/estimated_grams_males_add_vs_mult_MAIN.png", dpi=300, width=33, height=19, units="cm")

# Plots of additive only versus total estimates
female_grams_add_vs_mul <- plot_data_MAIN %>%
  filter(sex=="Female") %>%
  ggplot(aes(x=education)) +
  geom_point(aes(y=estAmn), colour = "grey") +
  geom_errorbar(aes(ymin = estAlo,
                    ymax = estAhi),
                colour="grey") +
  geom_point(aes(y=estmn), colour = "black") +
  geom_errorbar(aes(ymin = estlo,
                    ymax = esthi),
                colour = "black") +
  ylim(0, 4) +
  facet_grid(cols=vars(race),rows=vars(age)) +
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle=90))+
  ggtitle("Average daily alcohol consumption by intersectional category, for Women")+
  labs(y= "Estimated grams per day") +
  labs(caption = "Grey: estimate based on additive effects only  
Black: Estimate based on additive & interaction effects")
female_grams_add_vs_mul
ggsave("C:/Users/cmp21seb/Documents/SIMAH/SIMAH_workplace/nhis/intersectionality/plots/new spec August 2023/grams/estimated_grams_females_add_vs_mult_MAIN.png", dpi=300, width=33, height=19, units="cm")

