---
title: "R Notebook"
---

Setup
```{r, warning=FALSE}
# Read in data:
nhis_alc_clean <- readRDS("U:/SIMAH/SIMAH_workplace/nhis/intersectionality/cleaned_data/4_nhis_alc_clean.RDS")

# Generate a subset of drinkers
drinkers <- nhis_alc_clean %>% filter(ALCSTAT1 == "Current drinker")

# Read in necessary R packages & functions
library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ragg)

# Set default theme for plots:
theme_set(theme_bw(base_size = 12))
```

Explore ALC5UPYR distribution
```{r}
# Full sample
nhis_alc_clean %>% 
  count(ALC5UPYR) %>%
  mutate(percent = n/(sum(n))*100)

hist(nhis_alc_clean$ALC5UPYR, breaks = 100000)

# Drinkers only
drinkers %>% 
  count(ALC5UPYR) %>%
  mutate(percent = n/(sum(n))*100)

hist(drinkers$ALC5UPYR, breaks = 100000)
```
Majority (80% of full sample and 66% of drinkers) don't ever drink > 5 units

# Check if transformation of HED is appropriate as data highly skewed
```{r}
lambda <- forecast::BoxCox.lambda(drinkers$ALC5UPYR)  # 0.0099
# Value for lambda very close to 0 therefore log transformation appropriate

# generate a constant (half the value of the smallest positive value for ALC5UPYR)
c <- 0.5
drinkers$days_HED_log <- log(drinkers$ALC5UPYR + 0.5)
hist(drinkers$days_HED_log, breaks = 100000)
```
Appears no transformation is appropriate therefore need to generate binary variable

# Generate binary HED variable for drinkers
```{r}
Full_sample <- drinkers %>%
  mutate(HED =
    case_when(ALC5UPYR >= 1 ~ 1,
              ALC5UPYR == 0 ~ 0)
  )
```

# Explore proportion of HEDs by intersection
```{r}
# Generate intersections
Sample_HED <- Full_sample %>% 
  group_by(SEX, race_5_cats, education_3_cats, age_3_cats) %>% 
  mutate(intersections = cur_group_id())

Sample_HED <- Sample_HED %>% 
  mutate(intersectional_names = as.character(paste(SEX, age_3_cats,
                                                  race_5_cats,
                                                  education_3_cats))) %>%
  group_by(intersectional_names) %>%
  count(HED) %>%
  group_by(intersectional_names) %>%
  mutate(group_size = sum(n),
         HEDs = n,
         percent = n/sum(n)*100) %>%
  filter(HED==1) %>%
  arrange(desc(percent))

plot_data <- Sample_HED %>%
  mutate(sex=ifelse(grepl("F",intersectional_names),"Female","Male"),
         race=ifelse(grepl("Non-Hispanic Asian",intersectional_names),"Asian",
              ifelse(grepl("Non-Hispanic Black", intersectional_names),"Black",
              ifelse(grepl("Non-Hispanic Other", intersectional_names), "Other",
              ifelse(grepl("White", intersectional_names), "White","Hispanic")))),
         education=ifelse(grepl("high school", intersectional_names), "low edu.",
              ifelse(grepl("some college", intersectional_names), "medium edu.", "high edu.")),
            education=factor(education,levels=c("low edu.", "medium edu.", "high edu.")),
         age=ifelse(grepl("18-24", intersectional_names), "18-24",
         ifelse(grepl("25-69", intersectional_names), "25-69", "70+")))

# Plot
HED_plot <- plot_data %>%
  filter(group_size>= 100, HED == 1) %>%
  ggplot(aes(x=age, y=percent, colour=sex)) +
  geom_point() +
  facet_grid(cols=vars(education),rows=vars(race)) +
  theme(axis.title.x = element_blank(), legend.position = "bottom")+
  geom_hline(yintercept=26.1, linetype="dashed", color = "red") +
  ylim(0, 100) +
  ggtitle("Percentage reporting 1+ occassion of HED in last year") +
  labs(y= "percent") 
HED_plot

# Calculate mean percentage
Full_sample %>% ungroup() %>% group_by(HED) %>%(count)
# HED 98424 (26.1%)
```

